# Generated by Django 3.0.5 on 2020-07-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bambi', '0002_member_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_message', models.CharField(blank=True, max_length=500)),
                ('log_user_id', models.CharField(blank=True, max_length=50)),
                ('log_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
