# Generated by Django 3.0.5 on 2020-07-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bambi', '0003_auto_20200705_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_secondary_user_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
