# Generated by Django 3.0.5 on 2020-07-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bambi', '0004_log_log_secondary_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_secondary_message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
